import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { ValidationPipe } from '@nestjs/common';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  //! validating incoming requests using ValidationPipe, this will automatically validate the incoming requests based on the DTOs defined in the controllers, and will throw an error if the validation fails
  app.useGlobalPipes(
    new ValidationPipe({
      //! this is for remove the extra properties that are not defined in the DTO
      whitelist: true,

      //! this is for throw an error if there are extra properties that are not defined in the DTO
      forbidNonWhitelisted: true,

      //! this is for transform the payload to the DTO class instance
      transform: true,

      //! this is for disable the error messages that are generated by the validation pipe, this is useful for security reasons (if true, the error messages will not be sent to the client, but will be logged in the server console)
      disableErrorMessages: false,
    }),
  );

  await app.listen(process.env.PORT ?? 3000);
}
void bootstrap();
